# Generated by Django 4.0.4 on 2022-04-26 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=30, verbose_name='Nome do Tutor')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cep', models.CharField(max_length=9, verbose_name='Cep')),
                ('street', models.CharField(max_length=40, verbose_name='Rua')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('district', models.CharField(max_length=40, verbose_name='Bairro')),
                ('city', models.CharField(default='Petrolina', max_length=40, verbose_name='Cidade')),
                ('state', models.CharField(default='Pernambuco', max_length=40, verbose_name='Estado')),
            ],
            options={
                'ordering': ['tutor_name'],
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'ordering': ['vet_name'],
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30, verbose_name='Nome do Pet')),
                ('species', models.CharField(max_length=20, verbose_name='Espécie')),
                ('breed', models.CharField(max_length=30, verbose_name='Raça')),
                ('gender', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=5, verbose_name='Genêro')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('castrated', models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3, verbose_name='Castrado?')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Peso')),
                ('tutor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tutor', verbose_name='Nome do Tutor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('procedure', models.CharField(choices=[('Consulta', 'Consulta'), ('Retorno', 'Retorno'), ('Exame', 'Exame'), ('Cirurgia', 'Cirurgia')], max_length=8, verbose_name='Tipo de atendimento')),
                ('sedative', models.CharField(choices=[('Não', 'Não'), ('Simples', 'Simples'), ('Complexo', 'Complexo')], default='Não', max_length=8, verbose_name='Tipo de sedativo')),
                ('report', models.TextField(max_length=1000, verbose_name='Relato do problema')),
                ('pet_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pets', verbose_name='Nome do Pet')),
                ('vet_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vet', verbose_name='Veterinario')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
