# Generated by Django 4.0.3 on 2022-03-22 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id for Pet', primary_key=True, serialize=False)),
                ('pet_name', models.CharField(help_text='Enter a name of pet', max_length=30)),
                ('species', models.CharField(help_text='Enter a name of species', max_length=20)),
                ('breed', models.CharField(help_text='Enter a name of a animal breed', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Femea')], help_text='Enter a gender of a animal', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('castrated', models.CharField(blank=True, choices=[('N', 'Nao'), ('S', 'Sim')], default='N', max_length=1)),
                ('weight', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='species',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Procedures',
        ),
        migrations.DeleteModel(
            name='SpeciesOfPet',
        ),
    ]
