# Generated by Django 4.0.3 on 2022-03-23 14:50

import cpf_field.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pets_remove_procedures_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Data do atendimento', null=True)),
                ('time', models.TimeField(help_text='Hora do atendimento')),
                ('procedure', models.CharField(blank=True, choices=[('C', 'Consulta'), ('R', 'Retorno'), ('E', 'Exame'), ('C', 'Cirurgia')], help_text='Escolha o tipo do atendimento', max_length=1)),
                ('sedative', models.CharField(blank=True, choices=[('N', 'Nao'), ('S', 'Simples'), ('C', 'Complexo')], help_text='Escolha o tipo de sedativo', max_length=1)),
                ('report', models.TextField(blank=True, help_text='Relato do problema', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(help_text='Digite o nome do Tutor', max_length=30)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Digite seu telefone', max_length=31)),
                ('email', models.EmailField(help_text='Digite seu Email', max_length=254)),
                ('street', models.CharField(help_text='Digite a rua', max_length=40)),
                ('number', models.IntegerField(help_text='Digite o numero')),
                ('district', models.CharField(help_text='Digite a rua', max_length=40)),
                ('state', models.CharField(help_text='Digite a rua', max_length=40)),
                ('cep', models.IntegerField(help_text='Digite o cep')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(help_text='Nome do Veterinario', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pets',
            name='breed',
            field=models.CharField(help_text='Digite a raça do Pet', max_length=30),
        ),
        migrations.AlterField(
            model_name='pets',
            name='castrated',
            field=models.CharField(blank=True, choices=[('N', 'Não'), ('S', 'Sim')], default='N', help_text='Escolha se o Pet e castrado', max_length=1),
        ),
        migrations.AlterField(
            model_name='pets',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Digite a data de nascimento do Pet', null=True),
        ),
        migrations.AlterField(
            model_name='pets',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], help_text='Escolha o genêro do Pet', max_length=1),
        ),
        migrations.AlterField(
            model_name='pets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_name',
            field=models.CharField(help_text='Digite o nome do Pet', max_length=30),
        ),
        migrations.AlterField(
            model_name='pets',
            name='species',
            field=models.CharField(help_text='Digite a espécie do Pet', max_length=20),
        ),
        migrations.AlterField(
            model_name='pets',
            name='weight',
            field=models.DecimalField(decimal_places=3, help_text='Digite o peso do Pet', max_digits=6),
        ),
    ]
