# Generated by Django 4.0.4 on 2022-05-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_generalclinic_type_anamnese_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalclinic',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_anamnese',
            field=models.CharField(choices=[('Aula', 'Aula'), ('Rotina', 'Rotina')], max_length=6, verbose_name='Tipo anamnese'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_anti_rabica',
            field=models.CharField(choices=[('Não Vacinado', 'Não Vacinado'), ('Vacinado', 'Vacinado'), ('Não sabe', 'Não Sabe'), ('Desatualizada', 'Desatualizada'), ('Atualizada', 'Atualizada'), ('Não Ética', 'Não Ética'), ('Ética', 'Ética')], max_length=13, verbose_name='Anti-Rábica'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_ectopas',
            field=models.CharField(choices=[('Não', 'Não'), ('Não sabe Informar', 'Não Sabe Informar'), ('Desatualizada', 'Desatualizada'), ('Atualizada', 'Atualizada')], max_length=17, verbose_name='Prevenção Ectoparasitas'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_felina',
            field=models.CharField(choices=[('Não Vacinado', 'Não Vacinado'), ('Vacinado', 'Vacinado'), ('Não sabe', 'Não Sabe'), ('Desatualizada', 'Desatualizada'), ('Atualizada', 'Atualizada'), ('Não Ética', 'Não Ética'), ('Ética', 'Ética')], max_length=13, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_leish',
            field=models.CharField(choices=[('Não', 'Não'), ('Vacinado', 'Vacinado'), ('Usa Coleira', 'Usa    Coleira'), ('Atualizada', 'Atualizada'), ('Desatualizada', 'Desatualizada')], max_length=17, verbose_name='Prevenção Leishmaniose'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_type_felina',
            field=models.CharField(choices=[('Tríplice', 'Tríplice'), ('Quadrúpla', 'Quadrúpla')], max_length=9, verbose_name='Tríplice/Quádrupla Felina'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_type_v',
            field=models.CharField(choices=[('V8', 'V8'), ('V10', 'V10'), ('V12', 'V12')], max_length=3, verbose_name='V8/V10/V12'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_v',
            field=models.CharField(choices=[('Não Vacinado', 'Não Vacinado'), ('Vacinado', 'Vacinado'), ('Não sabe', 'Não Sabe'), ('Desatualizada', 'Desatualizada'), ('Atualizada', 'Atualizada'), ('Não Ética', 'Não Ética'), ('Ética', 'Ética')], max_length=13, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_verminose',
            field=models.CharField(choices=[('Não', 'Não'), ('Não sabe Informar', 'Não Sabe Informar'), ('Desatualizada', 'Desatualizada'), ('Atualizada', 'Atualizada')], max_length=17, verbose_name='Controle Verminose'),
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_conduct', models.CharField(choices=[('Dócil', 'Dócil'), ('Inquieto', 'Inquieto'), ('Medroso', 'Medroso'), ('Agressivo', 'Agressivo')], max_length=9, verbose_name='Conduta')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso')),
                ('choice_consciousness', models.CharField(choices=[('Coma', 'Coma'), ('Estupor', 'Estupor'), ('Confusão', 'Confusão'), ('Normal/Alerta', 'Normal/Alerta'), ('Sonolência/Apático', 'Sonolência/Apático'), ('Excitado', 'Excitado')], max_length=18, verbose_name='Nivel de Consciência')),
                ('stance', models.CharField(max_length=30, verbose_name='Postura')),
                ('hydration', models.CharField(max_length=30, verbose_name='Hidratação')),
                ('choice_nutricional_status', models.CharField(choices=[('Caquético', 'Caquético'), ('Magro', 'Magro'), ('Normal', 'Normal'), ('Gordo', 'Gordo'), ('Obeso', 'Obeso')], max_length=18, verbose_name='Estado Nutricional')),
                ('oculopalpebral', models.CharField(default='Não Permitiu', max_length=30, verbose_name='Mucosa Oculopalpebral')),
                ('bucal', models.CharField(default='Não Permitiu', max_length=30, verbose_name='Mucosa Bucal')),
                ('genital', models.CharField(default='Não Permitiu', max_length=30, verbose_name='Mucosa Genital')),
                ('choice_dental_calculus', models.CharField(choices=[('Não', 'Não'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso'), ('Não Permitiu', 'Não Permitiu')], max_length=18, verbose_name='Cálculo Dentário')),
                ('choice_dental_loss', models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim'), ('Persistência de dente decíduo', 'Persistência de dente decíduo'), ('Não Permitiu', 'Não Permitiu')], max_length=29, verbose_name='Perda Dentário')),
                ('gengivite', models.CharField(choices=[('Não', 'Não'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso'), ('Não Permitiu', 'Não Permitiu')], max_length=18, verbose_name='Gengivite')),
                ('choice_ulcera', models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim'), ('Não Permitiu', 'Não Permitiu')], max_length=12, verbose_name='Úlcera')),
                ('choice_halitose', models.CharField(choices=[('Não', 'Não'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso'), ('Não Permitiu', 'Não Permitiu')], max_length=18, verbose_name='Halitose')),
                ('linfonodos', models.CharField(max_length=30, verbose_name='Linfonodos')),
                ('fc', models.CharField(default=0, max_length=30, verbose_name='FC')),
                ('fr', models.CharField(default=0, max_length=30, verbose_name='FR')),
                ('tpc', models.CharField(default=0, max_length=30, verbose_name='TCP')),
                ('tr', models.CharField(default=0, max_length=30, verbose_name='TR')),
                ('pulse', models.CharField(default=0, max_length=30, verbose_name='Pulso')),
                ('choice_auscu_cardio', models.CharField(choices=[('Não Permitiu/Não Realizado', 'Não Permitiu/Não Realizado'), ('Bulhas Normofonéticas', 'Bulhas Normofonéticas'), ('Bulhas Hipofonéticas', 'Bulhas Hipofonéticas'), ('Sopro em Valva', 'Sopro em Valva')], max_length=26, verbose_name='Ausculta Cardíaca')),
                ('heart_rate', models.CharField(default=0, max_length=30, verbose_name='Ritmo Cardíaco')),
                ('choice_auscu_pulmonar', models.CharField(choices=[('Ruído Normal', 'Ruído Normal'), ('Alterado', 'Alterado'), ('Não Permitiu', 'Não Permitiu'), ('Não Realizado ACP', 'Não Realizado ACP')], max_length=17, verbose_name='Ausculta Pulmonar')),
                ('choice_percu_pulmonar', models.CharField(choices=[('Ndn (som claro)', 'Ndn (som claro)'), ('Submaciço', 'Submaciço'), ('Maciço', 'Maciço')], max_length=17, verbose_name='Percussão Pulmonar')),
                ('palpa_abdominal', models.CharField(max_length=30, verbose_name='Palpação Abdominal')),
                ('choice_mamas', models.CharField(choices=[('Ndn', 'Ndn'), ('Secreção', 'Secreção'), ('Hiperplasia', 'Hiperplasia')], max_length=17, verbose_name='Mamas/Tetos')),
                ('choice_nodulo', models.CharField(choices=[('Não', 'Não'), ('Firmes', 'Firmes'), ('Flutuante', 'Flutuante'), ('Aderido', 'Aderido'), ('Não Aderido', 'Não Aderido')], max_length=17, verbose_name='Nódulos')),
                ('choice_nodulo_pain', models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], max_length=30, verbose_name='Dor Nódulo')),
                ('choice_local_pain', models.CharField(choices=[('Lado Esquerdo', 'Lado Esquerdo'), ('Lado Direito', 'Lado Direito')], max_length=30, verbose_name='Localização da Dor')),
                ('choice_pain_m', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5')], max_length=3, verbose_name='')),
                ('genital_region', models.CharField(default='Normal', max_length=30, verbose_name='Região Genital')),
                ('choice_ectoparasitas', models.CharField(choices=[('Não', 'Não'), ('Carrapato', 'Carrapato'), ('Pulga', 'Pulga'), ('Miíase', 'Miíase')], max_length=30, verbose_name='Ectoparasitas')),
                ('ectoparasitas_intensity', models.CharField(max_length=30, verbose_name='Intensidade dos Parasitas')),
                ('pelage', models.CharField(default='Normal', max_length=30, verbose_name='Pelagem')),
                ('ears', models.CharField(default='Normal', max_length=30, verbose_name='Orelhas')),
                ('diag_differ', models.TextField(max_length=1000, verbose_name='Diagnósticos Diferenciais')),
                ('diag_final', models.TextField(max_length=1000, verbose_name='Diagnósticos Definitivos')),
                ('case_classification', models.CharField(choices=[('Caso Simples', 'Caso Simples'), ('Caso Complexo', 'Caso Complexo')], max_length=13, verbose_name='Classificação de caso')),
                ('medical_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medicalcare', verbose_name='Atendimento')),
            ],
        ),
    ]
