# Generated by Django 4.0.3 on 2022-03-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pets_medical_care_tutor_pet_vet_medical_care_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='medical_care',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='medical_care',
        ),
        migrations.AddField(
            model_name='medicalcare',
            name='pet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pets'),
        ),
        migrations.AddField(
            model_name='medicalcare',
            name='vet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vet'),
        ),
        migrations.AddField(
            model_name='pets',
            name='tutor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tutor'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='procedure',
            field=models.CharField(blank=True, choices=[('Consulta', 'Consulta'), ('Retorno', 'Retorno'), ('Exame', 'Exame'), ('Cirurgia', 'Cirurgia')], help_text='Escolha o tipo do atendimento', max_length=8),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='sedative',
            field=models.CharField(blank=True, choices=[('Não', 'Não'), ('Simples', 'Simples'), ('Complexo', 'Complexo')], default='N', help_text='Escolha o tipo de sedativo', max_length=8),
        ),
        migrations.AlterField(
            model_name='pets',
            name='castrated',
            field=models.CharField(blank=True, choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', help_text='Escolha se o Pet e castrado', max_length=3),
        ),
        migrations.AlterField(
            model_name='pets',
            name='gender',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], help_text='Escolha o genêro do Pet', max_length=5),
        ),
    ]
