# Generated by Django 4.0.3 on 2022-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_pets_medical_care_remove_tutor_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcare',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='sedative',
            field=models.CharField(blank=True, choices=[('Não', 'Não'), ('Simples', 'Simples'), ('Complexo', 'Complexo')], default='Não', help_text='Escolha o tipo de sedativo', max_length=8),
        ),
    ]
