# Generated by Django 4.0.4 on 2022-05-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_physicalexam_choice_pain_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDhermExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(max_length=500, verbose_name='Queixa principal')),
                ('choice_anamnese', models.CharField(choices=[('Aula', 'Aula'), ('Rotina', 'Rotina')], max_length=6, verbose_name='Tipo anamnese')),
                ('medical_care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medicalcare', verbose_name='Atendimento')),
            ],
        ),
    ]
