# Generated by Django 4.0.3 on 2022-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_medicalcare_id_alter_medicalcare_sedative'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='city',
            field=models.CharField(default='Petrolina', help_text='Digite a Cidade', max_length=40),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='state',
            field=models.CharField(default='Pernambuco', help_text='Digite o Estado', max_length=40),
        ),
    ]
