# Generated by Django 4.0.4 on 2022-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_generaldhermexam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldhermexam',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='choice_evolution_status',
            field=models.CharField(choices=[('Piorou', 'Piorou'), ('Melhorou', 'Melhorou'), ('Não evoluiu', 'Não evoluiu'), ('Não sabe', 'Não sabe')], default='-', max_length=30, verbose_name='Status da evolução'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='choice_prurido',
            field=models.CharField(choices=[('-', '-'), ('Esporádico', 'Esporádico'), ('Frequente', 'Frequente'), ('Sazonal', 'Sazonal'), ('Não sazonal', 'Não sazonal'), ('Diurno', 'Diurno'), ('Noturno', 'Noturno'), ('Nos dois períodos', 'Nos dois períodos')], default='-', max_length=17, verbose_name='Periodo do prurido'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='evolution_score',
            field=models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='-', max_length=2, verbose_name='Nota de evolução'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='evolution_time',
            field=models.CharField(default='-', max_length=30, verbose_name='Tempo de evolução'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='feels_intensity_topic',
            field=models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='-', max_length=2, verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='prurido',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Prurido'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='prurido_intensity',
            field=models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='-', max_length=2, verbose_name='Intensidade do prurido'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_01_where_begin',
            field=models.CharField(default='-', max_length=60, verbose_name='Onde as lesões iniciaram?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_02_how_are_lesions',
            field=models.CharField(default='-', max_length=60, verbose_name='Como eram as primeiras lesões?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_03_prurido_history',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='O prurido antecede as lesões?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_04_recent_medical_care',
            field=models.TextField(default='Não', max_length=200, verbose_name='Recentemente foi atendido por veterinário? - Quais exames realizados?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_05_aplication_prescrition_topic',
            field=models.TextField(default='Não', max_length=200, verbose_name='Foi aplicado ou prescrito algum produto tópico? (nome, dose, tempo de uso)'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_06_feels_better_topic',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Melhorou?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_07_feels_intensity_topic',
            field=models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='-', max_length=2, verbose_name='Foi usando antes ou depois do surgimento das lesões?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_08_aplication_prescrition_oral',
            field=models.TextField(default='Não', max_length=200, verbose_name='Foi aplicado ou prescrito algum produto via oral?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_09_feels_better_oral',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Melhorou?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_10_feels_intensity_oral',
            field=models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='-', max_length=2, verbose_name='Foi usando antes ou depois do surgimento das lesões?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_11_aplication_prescrition_oral',
            field=models.TextField(default='Não', max_length=200, verbose_name='É alérgico a algum fármaco/Produto? Quais?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_12_aplication_prescrition_oral',
            field=models.TextField(default='Não', max_length=200, verbose_name='Há histórico anterior de dermatopias? Exames realizados/Tratamento prescrito'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_13_color_skin',
            field=models.TextField(default='Não', max_length=200, verbose_name='Pele mudou de cor? / Quais áreas?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_14_color_fur',
            field=models.TextField(default='Não', max_length=200, verbose_name='Pelagem mudou de cor? / Quais áreas?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_15_dermatopias',
            field=models.TextField(default='Não', max_length=200, verbose_name='Há histórico de dermatopias familiar? / Quais áreas?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_16_persons_dermatopias',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Há lesões nas pessoas que convivem com o animal?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_17_contacts',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Contactantes?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_18_contacts_quant',
            field=models.CharField(default='Não', max_length=60, verbose_name='Espécie / Quantidade'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_19_contacts_assint',
            field=models.CharField(default='Assintomáticos', max_length=60, verbose_name='Assintomáticos / Sintomáticos'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_20_contacts_sint_quant',
            field=models.CharField(default='Não', max_length=30, verbose_name='Se sintomáticos, quantos? semelhante ao observado neste animal?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_21_contacts_sint_period',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei'), ('do paciente em atendimento foi antes', 'do paciente em atendimento foi antes'), ('do contactante foi antes', 'do contactante foi antes')], default='Não', max_length=36, verbose_name='As lesões apareceram no mesmo período?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_22_contacts_access_street',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Esporadicamente', 'Esporadicamente'), ('Frequentemente', 'Frequentemente'), ('Diariamente', 'Diariamente')], default='Não', max_length=15, verbose_name='Tem acesso à rua?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_23_contacts_sleep_local',
            field=models.CharField(choices=[('Fora de casa', 'Fora de casa'), ('Dentro de casa', 'Dentro de casa'), ('Os dois', 'Os dois')], default='Não', max_length=14, verbose_name='Local onde dorme / passa o dia?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_24_contacts_petbed',
            field=models.CharField(default='-', max_length=30, verbose_name='Onde o animal dorme? Sobre o que o animal se deita?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_25_contacts_wash_petbed',
            field=models.CharField(default='-', max_length=30, verbose_name='Como é feita a limpeza do local onde o animal dorme? Qual o produto?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_26_contacts_grass_earth',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Esporadicamente', 'Esporadicamente'), ('Frequentemente', 'Frequentemente'), ('Diariamente', 'Diariamente')], default='Não', max_length=15, verbose_name='Tem contato com terra e grama?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_27_contacts_plants',
            field=models.CharField(default='Não', max_length=30, verbose_name='Há plantas em casa ou que ele tenha contato?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_28_special_place',
            field=models.CharField(default='Não', max_length=30, verbose_name='Foi levado em algum em especial nos últimos meses?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_29_travel_cities',
            field=models.CharField(default='Não', max_length=30, verbose_name='Viaje para outras cidades?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_30_pulgas_carrapatos',
            field=models.CharField(choices=[('Não', 'Não'), ('Não sei', 'Não sei'), ('Sim', 'Sim'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso')], default='Não', max_length=15, verbose_name='Tem pulgas/carrapatos?'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_anamnese',
            field=models.CharField(choices=[('Aula', 'Aula'), ('Rotina', 'Rotina')], max_length=6, verbose_name='Tipo atendimento'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_felina',
            field=models.CharField(choices=[('Não Vacinado', 'Não Vacinado'), ('Não sabe', 'Não Sabe'), ('Vacinado, Desatualizada', 'Vacinado, Desatualizada'), ('Vacinado, Atualizada', 'Vacinado, Atualizada')], max_length=23, verbose_name='Opções Felina'),
        ),
        migrations.AlterField(
            model_name='generalclinic',
            name='choice_v',
            field=models.CharField(choices=[('Não Vacinado', 'Não Vacinado'), ('Não sabe', 'Não Sabe'), ('Vacinado, Desatualizada', 'Vacinado, Desatualizada'), ('Vacinado, Atualizada', 'Vacinado, Atualizada')], max_length=23, verbose_name='Opções V'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='choice_anamnese',
            field=models.CharField(choices=[('Aula', 'Aula'), ('Rotina', 'Rotina')], max_length=6, verbose_name='Tipo atendimento'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='gender',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=5, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='choice_local_pain',
            field=models.CharField(choices=[('Não', 'Não'), ('Lado Esquerdo', 'Lado Esquerdo'), ('Lado Direito', 'Lado Direito')], max_length=30, verbose_name='Local da Dor'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='choice_pain_m',
            field=models.CharField(choices=[('Não', 'Não'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5')], max_length=3, verbose_name='Código Região'),
        ),
    ]
