# Generated by Django 4.0.3 on 2022-04-08 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tutor_city_alter_tutor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcare',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='pet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pets', verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='procedure',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Retorno', 'Retorno'), ('Exame', 'Exame'), ('Cirurgia', 'Cirurgia')], max_length=8, verbose_name='Tipo de atendimento'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='report',
            field=models.TextField(max_length=1000, verbose_name='Relato do problema'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='sedative',
            field=models.CharField(choices=[('Não', 'Não'), ('Simples', 'Simples'), ('Complexo', 'Complexo')], default='Não', max_length=8, verbose_name='Tipo de sedativo'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='vet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vet', verbose_name='Veterinario'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='breed',
            field=models.CharField(max_length=30, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='castrated',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3, verbose_name='Castrado?'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='gender',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=5, verbose_name='Genêro'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_name',
            field=models.CharField(max_length=30, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='species',
            field=models.CharField(max_length=20, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='tutor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tutor', verbose_name='Nome do Tutor'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.IntegerField(help_text='Cep'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='city',
            field=models.CharField(default='Petrolina', max_length=40, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='district',
            field=models.CharField(max_length=40, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='state',
            field=models.CharField(default='Pernambuco', max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='street',
            field=models.CharField(max_length=40, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_name',
            field=models.CharField(max_length=30, verbose_name='Nome do Tutor'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
