# Generated by Django 4.0.4 on 2022-09-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_generaldhermexam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_31_previne_carrapatos',
            field=models.CharField(default='Sim', max_length=50, verbose_name='Previne? (Sim, Não - Produto):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_32_dose_freq',
            field=models.CharField(default='-', max_length=50, verbose_name='Dose / Frequência?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_33_food',
            field=models.CharField(default='APENAS Ração', max_length=50, verbose_name='Alimentação - Caseira, Ração(marca)?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_34_food_switch_freq',
            field=models.CharField(default='Não', max_length=50, verbose_name='Faz torca frequente de ração? (marcas usadas):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_35_food_diet_time',
            field=models.CharField(default='-', max_length=30, verbose_name='Há quanto tempo ingere esta dieta? (marcas usadas):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_36_water_offer',
            field=models.CharField(default='Torneira', max_length=25, verbose_name='Oferece água? (filtrada / torneira):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_37_homemade_food',
            field=models.CharField(default='-', max_length=100, verbose_name='Se come comida caseira, o que ja comeu?:'),
        ),
    ]
