# Generated by Django 4.0.3 on 2022-04-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_medicalcare_date_alter_medicalcare_pet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcare',
            name='pet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pets', verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='medicalcare',
            name='vet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vet', verbose_name='Veterinario'),
        ),
    ]
