# Generated by Django 4.0.3 on 2022-04-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_medicalcare_pet_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalcare',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['tutor_name']},
        ),
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['vet_name']},
        ),
    ]
