# Generated by Django 4.0.4 on 2022-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_generaldhermexam_quest_31_previne_carrapatos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_38_diarr',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Diarréia?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_39_diarr_food',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Relacionado a algum alimento?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_40_diarr_saz',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='É sazonal?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_41_material_things',
            field=models.CharField(default='-', max_length=50, verbose_name='De que material são feitos, vasilha de água, comida e brinquedos?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_42_solar_time',
            field=models.CharField(default='Não', max_length=30, verbose_name='Passa muito tempo em áreas com sol? (Em quais horários):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_43_feels_cold',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Sente muito frio?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_44_is_active',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=3, verbose_name='É ativo?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_45_hipoativo',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=3, verbose_name='Hipoativo?'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_34_food_switch_freq',
            field=models.CharField(default='Não', max_length=50, verbose_name='Faz troca frequente de ração? (marcas usadas):'),
        ),
    ]
