# Generated by Django 4.0.3 on 2022-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_medicalcare_options_alter_pets_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
