# Generated by Django 4.0.4 on 2022-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_generaldhermexam_quest_38_diarr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_46_agitado',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Normal', max_length=6, verbose_name='Muito agitado?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_47_anxiety',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Ansioso?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_48_anxiety_travel',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Fica ansioso quando alguém sai de casa ou viaja?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_49_wound_get_worse',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='As lesões pioram nessas situações?'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_50_family_change',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Houve mudanças com na familia? (Humano ou Pet)'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_51_family_change_affinity',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='-', max_length=3, verbose_name='Se sim, ele era apegado?'),
        ),
    ]
