# Generated by Django 4.0.4 on 2022-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_generaldhermexam_quest_46_agitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_52_family_change_house',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Houve mudança de casa?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_53_restrict_area_stay',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Restrição de área para o animal ficar?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_54_restrict_walk_play',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não passeio com ele', max_length=19, verbose_name='Restrição de passeio/brincadeiras?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_55_others_changes',
            field=models.CharField(default='-', max_length=50, verbose_name='Houveram outras mudanças no ambiente que possam desencadear ansiedade?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_56_lick_ends',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Lambe as extremidades?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_57_stay_alone',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Fica muito tempo sozinho?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_43_feels_cold',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Sente muito frio?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_45_hipoativo',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Sim', max_length=3, verbose_name='Hipoativo?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_46_agitado',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Normal', max_length=6, verbose_name='Muito agitado?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_47_anxiety',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Ansioso?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_48_anxiety_travel',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Fica ansioso quando alguém sai de casa ou viaja?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_49_wound_get_worse',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='As lesões pioram nessas situações?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_50_family_change',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Houve mudanças com na familia? (Humano ou Pet):'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_51_family_change_affinity',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='-', max_length=3, verbose_name='Se sim, ele era apegado?:'),
        ),
    ]
