# Generated by Django 4.0.3 on 2022-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tutor_cpf_alter_tutor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
