# Generated by Django 4.0.4 on 2022-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_generaldhermexam_quest_52_family_change_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_58_eat_differ',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Tomou algum medicamento ou comeu alguma coisa diferente antes de ocorrer o problema?:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_59_sneeze',
            field=models.CharField(default='Não', max_length=30, verbose_name='Há espirros? (Sim/Não - Frequência):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_60_nasal_eye_discharge',
            field=models.CharField(default='Não', max_length=30, verbose_name='Secreção nasal ou ocular? (Sim/Não - Frequência):'),
        ),
    ]
