# Generated by Django 4.0.4 on 2022-09-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_generaldhermexam_quest_58_eat_differ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_61_castrated',
            field=models.CharField(default='Não', max_length=50, verbose_name='Castrado? (Sim/Não - Com quantos anos/meses):'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_62_cio_frequence_anual',
            field=models.CharField(default='-', max_length=30, verbose_name='Frequência anual do cio:'),
        ),
        migrations.AddField(
            model_name='generaldhermexam',
            name='quest_63_cio_ausence',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=3, verbose_name='Ausência de cio?:'),
        ),
        migrations.AlterField(
            model_name='generaldhermexam',
            name='quest_60_nasal_eye_discharge',
            field=models.CharField(default='Não', max_length=50, verbose_name='Secreção nasal ou ocular? (Sim/Não - Frequência - Coloração):'),
        ),
    ]
